export const FETCH_POSTS="FETCH_POSTS"
export const LOGIN_VALIDATION="LOGIN_VALIDATION"
export const OLOGIN_VALIDATION="OLOGIN_VALIDATION"

//------------List props
export const LOCATION_INFO="LOCATION_INFO"
export const DETAILS_INFO="DETAILS_INFO"
export const BOOKINGOPS_INFO="BOOKINGOPS_INFO"
export const PHOTOS_INFO="PHOTOS_INFO"
export const PRICING_INFO="PRICING_INFO"
export const INSERT_PROPS="INSERT_PROPS"
